Implement 'cardano-wallet server' command to spin up an actual server
cardano-foundation/cardano-wallet pull request #155
Opened 2019-04-04 17:45 UTC by KtorZ

# Issue Number

#96 

# Overview

- [ ] I have implement the `cardano-wallet server` command to serve our API handlers
- [ ] I have fixed required `*HttpApi` instances required by Servant on a few path & query params
- [ ] I have fixed a wrong API endpoint which was missing a "passphrase" in the path

# Comments

Still a bit "rough", but does the job.

2019-04-04 21:11 UTC, piotr-iohk requested changes
lgtm (I suppose :))
However currently `cardano-wallet-launcher` does not spin up (i.e. doing `stack exec -- cardano-wallet-launcher` does not start `cardano-wallet server`). 

Not sure if this is a bug in docopt, but when I switched places of `--port` and `--network` it worked fine (https://github.com/input-output-hk/cardano-wallet/blob/master/app/launcher/Main.hs#L102-L107)

2019-04-05 07:19 UTC, KtorZ commented
@piotr-iohk So it's apparently a known issue from the docopt Haskell implementation (cf: https://github.com/docopt/docopt.hs#differences-from-reference-python-implementation) ...

\*sigh\* :disappointed: 

We may fix upstream eventually, but for now, I've fixed the argument position and added a disclaimer in the CLI definition.

2019-04-05 08:07 UTC, piotr-iohk approved these changes

2019-04-05 08:07 UTC, piotr-iohk commented
lgtm :+1:

2019-04-05 08:36 UTC, merged