Testing byron txs and migrations in Shelley
cardano-foundation/cardano-wallet pull request #1900
Opened 2020-07-13 10:15 UTC by piotr-iohk

# Issue Number

# Overview

- 66e5151f26172f957f50eab75e400b4e4c57384c
  Enable more integration tests for byron transactions, migrations, addresses and HW wallets in shelley
  
- d773d955a9990e33c3a51ba6613b87a365d7c7d3
  Add some special Byron and Icarus wallets to genesis for testing migration scenarios
  
- 834923ede8987b78eaf0cc9a32aa0f5b3582347d
  Use regular HSpec.it for tests that use explicit/special mnemonics, otherwise in case they fail, on repeat there will be a 409 as such wallet would exist
  

# Comments

2020-07-13 10:17 UTC, piotr-iohk commented on lib/core-integration/src/Test/Integration/Scenario/API/Byron/Transactions.hs
> -        let mnemonics =
I don't know how to generate this special legacy ledger wallet. For the moment I commented out this test.

2020-07-13 16:43 UTC, paweljakubas commented on lib/core-integration/src/Test/Integration/Scenario/API/Byron/TransactionsShelley.hs
> +      eventually "wa and wb balances are as expected" $ do
```suggestion
      eventually "wByron and wShelley balances are as expected" $ do
```

2020-07-13 16:45 UTC, paweljakubas approved these changes
LGTM!

2020-07-13 17:01 UTC, piotr-iohk commented
bors r+

2020-07-14 05:52 UTC, piotr-iohk commented
bors r+

2020-07-14 09:12 UTC, piotr-iohk commented
Tests timeout in CI. Locally running integration tests and they run already for an ~1h. I think the problem is that there is a manifestation of this error (https://github.com/input-output-hk/cardano-wallet/issues/1708) or something similar going on which makes a lot of test stuck on `eventually` step and fail... (Trying to list shelley wallets on the wallet from integration tests, while they are running shows `500`)

Perhaps some tests I enabled are causing this... I'll try to isolate.

2020-07-14 09:13 UTC, rvl commented
@piotr-iohk it says the tests were taking longer than 45 minutes.
Are they getting stuck, or do we need to increase the timeout?
Timeout is here: https://github.com/input-output-hk/cardano-wallet/blob/master/.buildkite/rebuild.hs#L151
In Buildkite you can see the stack log files under the "Artifacts" tab.

2020-07-14 09:42 UTC, piotr-iohk commented
Running locally I got:
```
Finished in 4349.0001 seconds
643 examples, 297 failures, 3 pending
```
All failures are:
```
       DecodeFailure "{\"code\":\"wallet_not_responding\",
\"message\":\"That's embarassing. My associated worker for 07981b66dda508d67d8b212ca3ecacafa6d505fd is no longer responding. This is not something that is supposed to happen. 
The worker must have left a trace in the logs of severity 'Error' when it died which might explain the cause. Said differently, this wallet won't be accessible until the server is restarted but there are good chances it'll recover itself upon restart.\"}"

```
@rvl so I don't think increasing timeout will help...
Some test could be causing this or this (#1708) "just" happens at some point which causes subsequent test to fail.

2020-07-14 14:06 UTC, piotr-iohk commented
I'm not able to isolate a specific test but the issue seems to be happening while running tests tagged `BYRON_MIGRATIONS`... running tests from there 1 by 1 appears to be fine... :thinking:

2020-07-16 12:26 UTC, piotr-iohk commented
tests passed for me locally after rebasing. :man_shrugging:

2020-07-16 12:26 UTC, piotr-iohk commented
bors try

2020-07-17 06:26 UTC, rvl commented
bors r+

2020-07-17 06:26 UTC, rvl approved these changes

2020-07-18 09:11 UTC, piotr-iohk commented
bors r+

2020-07-18 20:34 UTC, paweljakubas commented
@rvl  @piotr-iohk  I wonder if we don't need to increase CI timeouts to accommodate those new scenarios

2020-07-20 13:27 UTC, piotr-iohk commented
bors r+

2020-07-20 14:43 UTC, piotr-iohk commented
bors try

2020-07-21 08:57 UTC, piotr-iohk commented
I'm not sure what is the problem:
```
killed after writing more than 67108864 bytes of log output
```
(included in the CI failures spreadsheet)

The suite passes now for me locally:
```
Finished in 1365.8492 seconds
646 examples, 0 failures, 3 pending
```

2020-07-21 08:59 UTC, piotr-iohk commented
bors r+

2020-07-22 08:54 UTC, piotr-iohk commented
bors r+

2020-07-22 10:35 UTC, piotr-iohk commented
Again:
```
killed after writing more than 67108864 bytes of log output
```
:(

2020-07-23 14:30 UTC, piotr-iohk commented
bors r+

2020-07-24 14:26 UTC, piotr-iohk commented
bors r+

2020-07-24 15:48 UTC, KtorZ requested changes
Please let's merge this one after #1909. In particular, #1909 will re-introduce scenarios for Byron wallets as well as migration from Byron to Shelley already.

2020-07-25 11:00 UTC, piotr-iohk commented
We might as well close this one if #1909 has equivalent scenarios.

2020-07-30 12:21 UTC, closed without merging