Variable pipelining to optimize memory usage in the wallet restoration phase
cardano-foundation/cardano-wallet pull request #3274
Opened 2022-05-12 14:55 UTC by paolino

- I have implemented a pipelining number that depends on blockheight

### Issue Number

ADP-1765

2022-05-12 17:02 UTC, Anviking reviewed
Will look more tomorrow

2022-05-12 17:02 UTC, Anviking commented on lib/core/src/Ouroboros/Network/Client/Wallet.hs
> +chainSyncWithBlocks tr pipeliningStrategy chainFollower =
Nice! 👍  Seems neater than both 1) retro-fitting `rollForward` or 2) adding another callback to `ChainFollower`.

2022-05-12 17:02 UTC, Anviking commented on lib/shelley/bench/latency-bench.hs
> +import Cardano.Wallet.PipeliningStrategy
Could you make this and the similar imports explicit?

From our coding standards:

> We use explicit imports by default, and favor qualified imports for ambiguous functions

https://input-output-hk.github.io/adrestia/code/Coding-Standards#we-use-explicit-imports-by-default-and-favor-qualified-imports-for-ambiguous-functions

2022-05-12 17:02 UTC, Anviking commented on lib/shelley/src/Cardano/Wallet/PipeliningStrategy.hs
> +module Cardano.Wallet.PipeliningStrategy where
We tend to use explicit module export lists. Could you use that here as well?

2022-05-12 17:02 UTC, Anviking commented on lib/core/src/Ouroboros/Network/Client/Wallet.hs
> +                            $ NE.last blocks'
```suggestion
                            $ block
```

Not sure if it actually has any difference for performance, but this should be the same thing right?

2022-05-12 17:02 UTC, Anviking commented on lib/shelley/src/Cardano/Wallet/PipeliningStrategy.hs
> +    -> ([(Quantity x y, Natural)], Natural)
What about specialising this for readability to our de-facto BlockNo type?
```suggestion
    -> ([(Quantity "block" Natural, Natural)], Natural)
```

(Btw, I wonder if not we should use `Cardano.Slotting.BlockNo` in the wallet instead, but that's unrelated to this)

2022-05-12 17:02 UTC, Anviking commented on lib/shelley/src/Cardano/Wallet/PipeliningStrategy.hs
> +    , 50
🧐 I feel like something like this would be more readable:

```haskell
pipeliningOfStrat VariablePipeLining blockNo
    | blockNo <= 4_000_000 = Pipelining 1000
    | blockNo <= 5_000_000 = Pipelining 200
    | blockNo <= 6_000_000 = Pipelining 200
    | otherwise            = Pipelining 50
```

2022-05-13 06:39 UTC, paolino commented on lib/core/src/Ouroboros/Network/Client/Wallet.hs
> +chainSyncWithBlocks tr pipeliningStrategy chainFollower =
Heinrich is father here :-)

2022-05-13 06:39 UTC, paolino commented on lib/shelley/bench/latency-bench.hs
> +import Cardano.Wallet.PipeliningStrategy
Yes, how do you check this usually?

2022-05-13 06:40 UTC, paolino commented on lib/shelley/src/Cardano/Wallet/PipeliningStrategy.hs
> +module Cardano.Wallet.PipeliningStrategy where
Yes

2022-05-13 06:42 UTC, paolino commented on lib/core/src/Ouroboros/Network/Client/Wallet.hs
> +                            $ NE.last blocks'
should be the same but hlint does not agree on style as default, so I tend to not do it. Is this our code of code?

2022-05-13 06:43 UTC, paolino commented on lib/shelley/src/Cardano/Wallet/PipeliningStrategy.hs
> +    -> ([(Quantity x y, Natural)], Natural)
Yes, that module is really a draft, I will specialize that.

2022-05-13 06:44 UTC, paolino commented on lib/shelley/src/Cardano/Wallet/PipeliningStrategy.hs
> +    , 50
agreed

2022-05-13 06:48 UTC, paolino commented on lib/shelley/bench/latency-bench.hs
> +import Cardano.Wallet.PipeliningStrategy
HLS  does not work for me on that file, does it for you?

2022-05-13 06:51 UTC, paolino commented on lib/shelley/bench/latency-bench.hs
> +import Cardano.Wallet.PipeliningStrategy
I propose, for that reason that we limit the amount of code in the exe file and keep only a 
```haskell
import qualified Cardano.Wallet.Benchmarks.Latency
main = Cardano.Wallet.Benchmarks.Latency.main
```
in the file

2022-05-13 06:57 UTC, paolino commented on lib/core/src/Ouroboros/Network/Client/Wallet.hs
> +chainSyncWithBlocks tr pipeliningStrategy chainFollower =
Btw, this whole thing is a hack. There should be a better interface against the node, with byte constraints on the pipeline, with a minimum unnegotiable of 1 block

2022-05-16 13:02 UTC, HeinrichApfelmus requested changes
I really like the `PipeliningStrategy` encapsulation 😊 — and recommend to focus the types on it. See comments.

2022-05-16 13:02 UTC, HeinrichApfelmus commented on lib/shelley/src/Cardano/Wallet/PipeliningStrategy.hs
> +module Cardano.Wallet.PipeliningStrategy
Could you merge this module into `Ouroboros.Network.Client.Wallet` or move it into the `Cardano.Wallet.Network.*` hierarchy? This would make it more clear that pipelining is a networking concept.

This requires ditching `CardanoBlock StandardCrypto` and related imports. Use the `HasHeader` class from `Ouroboros.Network.Block` instead, it contains enough information to get the block height (called "block number" there). This also allows you to get rid of the additional `NetworkParameters` argument.

2022-05-16 13:02 UTC, HeinrichApfelmus commented on lib/shelley/src/Cardano/Wallet/PipeliningStrategy.hs
> +        . fromCardanoBlock (genesisParameters gp)
I'm very fond of the introduction of the `PipeliningStrategy` type — it's a nice abstraction / encapsulation. 😊

However, I think that the code benefits if random assorted types such as `PredefinedPipeliningStrategy` are not used and instead everything is focused on the `PipeliningStrategy` type. I recommend to implement the following

### Interface
```hs

data PipeliningStrategy

instance Show PipeliningStrategy

getPipelineSize :: PipeliningStrategy -> Quantity "block" Word32 -> Integer

mainnet :: PipeliningStrategy
thousand :: PipeliningStrategy

```

In particular, `mainnet` and `thousand` are "bona fide pipelining stragies", no need to use a constructor to make them more "tangible" (e.g. `show`able).

### Implementation 

As before.

You can get the `Show` instance by making the string to be shown part of the `data` type:

```hs
data PipeliningStrategy = PipeliningStrategy
    { getPipelineSize :: Quantity "block" Word32 -> Integer
    , name :: Text
    }

mainnet = PipeliningStrategy { name = "VariablePipelining", … }
```

2022-05-16 13:40 UTC, Anviking commented on lib/shelley/src/Cardano/Wallet/PipeliningStrategy.hs
> +        . fromCardanoBlock (genesisParameters gp)
Perhaps the name `mainnet` could be confusing when we also use it for testnet? 🤔  (And I'm not sure not using it for testnet is better) Perhaps a slightly more awkward `tunedForMainnet` or generic `default` instead?

2022-05-16 13:48 UTC, Anviking commented on lib/shelley/bench/latency-bench.hs
> +import Cardano.Wallet.PipeliningStrategy
I use @rvl's `ln -s hie-direnv.yaml hie.yaml` and it usually works pretty decent in all targets, including in this file

2022-05-16 14:10 UTC, Anviking commented on lib/core/src/Ouroboros/Network/Client/Wallet.hs
> +                            $ NE.last blocks'
> should be the same but hlint does not agree on style as default, so I tend to not do it. Is this our code of code?

What do you mean? I don't get any warnings

I'm worried about the `NE.last` having O(n) time complexity, where we might as well use `block` to get O(1).

2022-05-16 14:17 UTC, HeinrichApfelmus commented on lib/shelley/src/Cardano/Wallet/PipeliningStrategy.hs
> +        . fromCardanoBlock (genesisParameters gp)
I like `tunedForMainnet` 😊

2022-05-16 14:48 UTC, Anviking commented on lib/shelley/exe/local-cluster.hs
> +    ( variablePipelining )
This import should be moved to the first section along the other normal, not qualified ones.

2022-05-16 14:49 UTC, Anviking commented on lib/core/src/Ouroboros/Network/Client/Wallet.hs
> +        ::  [block]
```suggestion
       ::  [block]
```

2022-05-17 07:13 UTC, paolino commented on lib/core/src/Ouroboros/Network/Client/Wallet.hs
> +                            $ NE.last blocks'
oh ok, I got it completely wrong, my bad. I thought it was a syntactic hint

2022-05-17 11:19 UTC, HeinrichApfelmus reviewed
Punchier names! ✊

For example, I have no idea how to explain the meaning and purpose of the `Pipelining` type succinctly. But I can explain `getPipelineSize`: "`getPipelineSize` returns the size of the pipeline that should be used after encountering the given `block` (height)". Hence, I recommend to inline the type names.

2022-05-17 11:19 UTC, HeinrichApfelmus commented on lib/shelley/bench/restore-bench.hs
> +                (T.unpack $ benchname
I think that the filepath merits a name, brought into scope using `let` or `where`.

```
timelogFilepath = T.unpack $ benchname <> "." <> …
```

2022-05-17 11:19 UTC, HeinrichApfelmus commented on lib/shelley/src/Cardano/Wallet/Shelley/Network/Node.hs
> +                let client = mkWalletClient
```suggestion
                let client = mkWalletClient
```

2022-05-17 11:19 UTC, HeinrichApfelmus commented on lib/shelley/test/unit/Cardano/Wallet/Shelley/NetworkSpec.hs
> +                testnet np sock vData sTol $ \nl -> do
Style: I prefer an indentation style that visually distinguishes functions from their arguments.

If this was a `do` block, then `tunedForMainnetPipeliningStrategy` and `testnet` would be separate statements instead of arguments to `withNetworkLayer`. The only visual distinction would be the presence or absence of a small `do` — which I have to go looking for in order to parse this code correctly.

```suggestion
                withNetworkLayer tr
                    tunedForMainnetPipeliningStrategy
                    testnet np sock vData sTol $ \nl -> do
```

2022-05-17 11:19 UTC, HeinrichApfelmus commented on lib/core/src/Ouroboros/Network/Client/Wallet.hs
> +    }
```suggestion
-- | Pipelining strategies
data PipeliningStrategy block = PipeliningStrategy
    { getPipelineSize :: block -> Natural
    , pipeliningStrategyName :: Text  
    }
```

Naming things is a hard problem, but totally worth solving. 🤓 This is a good time to inline the names: `Pipelining` and `PipeliningOfBlock` are too non-descriptive to be helpful, whereas `getPipelineSize` does what it says.

2022-05-17 11:50 UTC, HeinrichApfelmus approved these changes
One last style issue to fix, then it's good to go! 😊

2022-05-17 11:50 UTC, HeinrichApfelmus commented on lib/core/src/Ouroboros/Network/Client/Wallet.hs
> +import Data.Text (Text)
This import should be moved to the section just above containing other unqualified imports.

(https://input-output-hk.github.io/adrestia/code/Coding-Standards#stylish-haskell-is-used-to-format-grouped-imports--language-pragmas )

2022-05-17 13:04 UTC, jonathanknowles reviewed
Hi @paolino 

There are a few sections of the code that are in excess of our [line length limit](https://input-output-hk.github.io/adrestia/code/Coding-Standards#limit-line-length-to-80-characters). Would it be possible to amend those before merging?

Many thanks!

Jonathan

2022-05-17 13:04 UTC, jonathanknowles commented on lib/shelley/bench/restore-bench.hs
> +        , benchRestoreMultipleWallets 100 (unsafeMkPercentage 0.01) tunedForMainnetPipeliningStrategy
Hi @paolino 

Would it be possible to reformat this block to follow our [line length limit](https://input-output-hk.github.io/adrestia/code/Coding-Standards#limit-line-length-to-80-characters)?

Many thanks!

There are lots of ways we could do this. For example:

```suggestion
        , benchRestoreSeqWithOwnership (Proxy @0)
            tunedForMainnetPipeliningStrategy
        , benchRestoreSeqWithOwnership (Proxy @1)
            tunedForMainnetPipeliningStrategy
        , benchRestoreRndWithOwnership (Proxy @1)
            tunedForMainnetPipeliningStrategy
        , benchRestoreMultipleWallets 1 (unsafeMkPercentage 0.1)
            tunedForMainnetPipeliningStrategy
        , benchRestoreMultipleWallets 10 (unsafeMkPercentage 0.01)
            tunedForMainnetPipeliningStrategy
        , benchRestoreMultipleWallets 100 (unsafeMkPercentage 0.01)
            tunedForMainnetPipeliningStrategy
```

2022-05-17 13:04 UTC, jonathanknowles commented on lib/shelley/bench/restore-bench.hs
> +                    action progressTrace nw
https://input-output-hk.github.io/adrestia/code/Coding-Standards#limit-line-length-to-80-characters

```suggestion
        withWalletLayerTracer benchName pipeliningStrat traceToDisk $
            \progressTrace -> withNetworkLayer
                networkTrace
                pipeliningStrat
                networkId np socket vData sTol $
                    \nw -> action progressTrace nw
```

2022-05-17 13:04 UTC, jonathanknowles commented on lib/shelley/bench/restore-bench.hs
> +                withWalletLayerTracer benchname pipeliningStrat traceToDisk $ \progressTrace -> do
```suggestion
            withBenchDBLayer @s @k ti wlTr $ \db -> do
                let withWalletLayer =
                        withWalletLayerTracer benchname pipeliningStrat traceToDisk
                withWalletLayer $ \progressTrace -> do
```

2022-05-18 06:16 UTC, paolino commented
bors r+

2022-05-18 07:37 UTC, paolino commented
bors r+

2022-05-18 08:12 UTC, merged