[ADP-2367] Implementation of  `DBPendingTxs` using a `DBVar` for `DeltaTxSubmissions`
cardano-foundation/cardano-wallet pull request #3703
Opened 2023-01-19 15:05 UTC by HeinrichApfelmus

### Overview

This pull request extracts changes from #3673 for the purpose of merging them.

Here, we extract an implementation of the `DBPendingTxs` interface given a `DBVar` for the `TxSubmissions` data type. This implementation is *partial* in that it still contains calls to `error` which need to be resolved — however, this requires changes to the interface at the usage site.

Also, this pull request does not yet make an attempt at integrating this implementation of `DBPendingTxs` with the rest of the wallet.

### Issue Number

ADP-2367

2023-01-19 17:20 UTC, paolino requested changes
should we remove the migration.md ?

2023-01-19 17:20 UTC, paolino commented on lib/wallet/src/Cardano/Wallet/DB/Store/Submissions/New/Operations.hs
> +    ( nub )
issue with imports

2023-01-20 09:15 UTC, HeinrichApfelmus commented on lib/wallet/src/Cardano/Wallet/DB/Store/Submissions/New/Operations.hs
> +    ( nub )
Fixed, thanks.

2023-01-20 13:09 UTC, HeinrichApfelmus commented
I have addressed the requested changes so far. Happy to address more if desired.

2023-01-20 13:14 UTC, paolino commented
> 

bors it

2023-01-20 13:28 UTC, HeinrichApfelmus commented
> bors it

I'd be happy to, but the pull request is lacking your stamp of approval. 🥺 You have to select the checkbox with "Approve" rather than "Request changes" somewhere. 🤔 



<img width="642" alt="Screen Shot 2023-01-20 at 14 28 18" src="https://user-images.githubusercontent.com/564592/213705965-6324f80f-b032-4389-a5c9-e51b2b454e6b.png">

2023-01-20 13:55 UTC, paolino approved these changes
Thanks

2023-01-20 13:55 UTC, paolino commented
bors r+

2023-01-20 14:24 UTC, merged