Scaffold Jörmungandr TransactionLayer and Jörmungandr postTx
cardano-foundation/cardano-wallet pull request #418
Opened 2019-06-16 22:19 UTC by Anviking

# Issue Number

# Overview

The goal here is to be able to "throw transactions at jörmungandr" as soon as possible.

- Added `JörmungandrLayer` `postTx`
- `TransactionLayer` with mkStdTx and _very_ unfinished size estimation.

# Comments

`stack ghci cardano-wallet-jormungandr` + separate `cd lib/jormungandr/test/data/jormungandr/; jormungandr --genesis-block block-0.bin --config config.yaml --secret secret.yaml`
```haskell
import Cardano.Wallet.Jormungandr.Network
import Cardano.Wallet.Primitive.Types
import Cardano.Wallet.Network
import Cardano.Wallet
:m -Cardano.Wallet.Jormungandr.Binary

:set -XTypeApplications
:set -XDataKinds

mgr <- newManager defaultManagerSettings
let j = mkJormungandrLayer mgr (BaseUrl Http "localhost" 8081 "/api")
let absentParent = Hash "\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL"
[block0Id] <- unsafeRunExceptT $ getDescendantIds j absentParent 1
block0 <- unsafeRunExceptT $ getBlock j block0Id

wallet <- newWalletLayer @_ @(Jormungandr 'Mainnet) block0 db nw tl

coerce (Hash a) = Hash a
tl = newTransactionLayer @'Mainnet (coerce block0Id)

-- tx from the genesis block
let tx = Tx [] [TxOut {address = Address {unAddress = "\131\&3$\195xi\193\"h\154\&5\145}\245:O\"\148\163\165/h^\ENQ\245\248\229;\135\231\234E/"}, coin = Coin {getCoin = 14}}]
let stx = (tx, [])
unsafeRunExceptT $ postSignedTx j stx 

--  Exception: user error (unexpected error: ErrPostTxBadRequest "")
```

2019-06-16 22:38 UTC, Anviking commented
FYI @akegalj

2019-06-17 12:03 UTC, KtorZ requested changes
I am not really sure about the transaction part... Maybe I was wrong saying that getting to make transaction was urgent; it is, but it doesn't mean we've to cut on quality or software reliability. There are parts that can be left out like the fee calculation, but let's get the signing part done right, and with testing.

2019-06-17 12:03 UTC, KtorZ commented on lib/jormungandr/src/Cardano/Wallet/Jormungandr/Transaction.hs
> +    sizeOfAddress = 32
There are also different sizes of addresses I believe. Which can be easily figured out by measuring the length of the `Address` payloads. Remains the change coins for which we haven't _yet_ generated an address, but those ones would be new bech32 addresses so 33 bytes.

2019-06-17 12:03 UTC, KtorZ commented on lib/jormungandr/src/Cardano/Wallet/Jormungandr/Transaction.hs
> +    sizeOfTxWitness = 128
For now, will always be new witness scheme. We'll see later how / if we choose to support old wallets with new ones. Anyway, it's possible to figure out the kind of witness to produce from the type of address we need to produce witness for.

2019-06-17 12:03 UTC, KtorZ commented on lib/jormungandr/src/Cardano/Wallet/Jormungandr/Transaction.hs
> +    sizeOfOutput = sizeOfAddress + 8
Where does the `+ 8` ? comes from ? (and same for the `+1` above)

2019-06-17 12:03 UTC, KtorZ commented on lib/jormungandr/src/Cardano/Wallet/Jormungandr/Transaction.hs
> +mkWitness (WitnessData dat) (xPrv, pwd) =
Why the `WitnessData` indirection here? Why not have the hashes as arguments directly?

2019-06-17 12:03 UTC, KtorZ commented on lib/jormungandr/src/Cardano/Wallet/Jormungandr/Transaction.hs
> +import Cardano.Wallet.Jormungandr.Compatibility
Explicit import here :point_up:

2019-06-17 12:03 UTC, KtorZ commented on lib/jormungandr/src/Cardano/Wallet/Jormungandr/Transaction.hs
> +    :: forall n . Hash "Block0Hash"
I am not sure about this type ...  And, does this really have to be the hash from the first block header?

2019-06-17 12:03 UTC, KtorZ commented on lib/jormungandr/src/Cardano/Wallet/Jormungandr/Network.hs
> +                    return $ Left $ ErrPostTxProtocolFailure msg
It'll be best to do the "other way around". Don't try to do the error handling upfront, write tests and see what sort of error handling you need...

2019-06-17 12:03 UTC, KtorZ commented on lib/jormungandr/src/Cardano/Wallet/Jormungandr/Transaction.hs
> +    , estimateSize = \(CoinSelection inps outs chngs) ->
This can probably be left out for know by the way and implemented as `const (Quantity 0)`. Jormungandr doesn't support fee anyway at the moment...

2019-06-17 14:13 UTC, closed without merging