[ADP-3344] Implement `rollBackward` for the Deposit Wallet
cardano-foundation/cardano-wallet pull request #4776
Opened 2024-09-16 14:12 UTC by HeinrichApfelmus

This pull request implements the `rollBackward` function for the Deposit Wallet.

* We use the `RollbackWindow` data type to decide whether we need to roll back all the way back to genesis.
* The `Cardano.Wallet.Deposit.Pure.Submissions` module remains a mock implementation for now.

### Issue Number

ADP-3344

2024-09-30 11:35 UTC, paolino requested changes

2024-09-30 11:35 UTC, paolino commented on lib/customer-deposit-wallet/test/unit/Cardano/Wallet/Deposit/PureSpec.hs
> +payFromFaucet :: [(Write.Address, Write.Value)] -> Read.Tx
What about other types of txs, like spending from our addresses ?

2024-09-30 15:52 UTC, HeinrichApfelmus commented on lib/customer-deposit-wallet/test/unit/Cardano/Wallet/Deposit/PureSpec.hs
> +payFromFaucet :: [(Write.Address, Write.Value)] -> Read.Tx
I agree, a test that rolling back a spent input works is desirable. I have added a mock function `spendOneTxOut` and used it.

This is as far as I would like to take testing this feature for now. I'll add documentation for the properties that we would expect on a rollback to the Agda code.

2024-10-01 14:05 UTC, paolino approved these changes
:bow:

2024-10-02 20:35 UTC, merged