Use SlotNo instead of SlotId in core wallet
cardano-foundation/cardano-wallet pull request #563
Opened 2019-07-18 06:05 UTC by rvl

Relates to issue #465

# Overview

This changes `SlotId` (epoch, local slot index) to `SlotNo` (0-based index, number of slots since genesis) in the wallet core. The wallet then needs to worry even less about slotting. Network node backends handle conversion according to their configuration (and, in future, chain state).

On top of this, the network layers can provide a function `slotTime :: Monad m => NetworkLayer -> SlotNo -> m UTCTime`, using their configuration (and, in future, chain state).

# Comments

Not all the tests and benchmarks have been refactored yet.

2019-07-18 09:34 UTC, Anviking commented on lib/core/src/Cardano/Wallet/Primitive/Types.hs
> +  using their configuration and chain state.
I am still not convinced having the `NetworkLayer` be aware of the chain-state is a good idea. I think I am afraid of race-conditions between the following:
- `Wallet`/`Checkpoint` state
- `NetworkLayer` state (some kind of `MVar (Map Epoch BlockchainParameters)`?)
- Short rollbacks (that change blockchain parameters in the EBB)
- Long rollbacks (larger than one epoch)
- Multiple wallets restoring at different positions in the chain simultaneously

2019-07-18 11:35 UTC, KtorZ commented
@rvl How do you anticipate the network layer to keep track of the epoch/slot chain parameters?

2019-07-19 05:47 UTC, rvl commented
Thanks for your thoughts...

> I am still not convinced having the NetworkLayer be aware of the chain-state is a good idea. I think I am afraid of race-conditions.

@Anviking The network layer is the best place to manage it. This is where rollbacks and parameter updates come from. The wallet core will be simpler if it doesn't need to worry about the length of epochs or slots. There won't be race-conditions because the network layer will be the single source of truth.

> How do you anticipate the network layer to keep track of the epoch/slot chain parameters?

It will read the config parameters at startup (done in this PR). Then it will maintain a mutable variable tracking the list of epoch lengths. SlotId flattening is done when decoding blocks.

2019-07-23 03:20 UTC, jonathanknowles requested changes
Hi @rvl. I've had a look through and left some comments.

Although the change looks sound, I'm not sure I fully understand all the ramifications.

Some questions:
1. Are the epoch lengths of different backends allowed to be different?
2. Is the epoch length ever allowed to change?

2019-07-23 03:20 UTC, jonathanknowles commented on lib/core/src/Cardano/Wallet/DB/Sqlite.hs
> +    , txMetaSlot = meta ^. #slotNo
Maybe call this `txMetaSlotNo`, for consistency?

2019-07-23 03:20 UTC, jonathanknowles commented on lib/core/src/Cardano/Wallet/DB/Sqlite/TH.hs
> +    txMetaSlot       W.SlotNo     sql=slot
Perhaps we can have `sql=slot_no` as well?

2019-07-23 03:20 UTC, jonathanknowles commented on lib/core/src/Cardano/Wallet/Primitive/Types.hs
> +  deriving newtype (Num, Enum)
Given that `fromEnum` trims values to `Int`, I wondered whether this was safe. However, it turns out that this should be still good for another 2000 years. (120s × (2^29 − 1)) ≈ 2000 years.

2019-07-23 03:20 UTC, jonathanknowles commented on lib/core/src/Cardano/Wallet/Primitive/Types.hs
> +        Quantity $ toEnum $ fromIntegral $ (100 * a) `div` b
Hi @rvl. Not related to your change per se, but on seeing this code for the first time, I wonder why we choose to compute `slotRatio` in this way.

If the idea behind using `tolerance` is to solve the problem that the progress never quite reaches 100%, then wouldn't it be easier, when calculating the ratio, to round up, instead of down?

Something like this:
```hs
import Data.Ratio ((%))

...

slotRatio (SlotNo a) (SlotNo b)
    | a >= b = maxBound
    | otherwise = Quantity $ toEnum $ ceiling $ (100 * a) % b
```

2019-07-23 03:20 UTC, jonathanknowles commented on lib/core/test/unit/Cardano/Wallet/Primitive/TypesSpec.hs
> +    shrink _ = []
Why no shrinking allowed here?

2019-07-23 03:20 UTC, jonathanknowles commented on lib/core/test/unit/Cardano/Wallet/Primitive/TypesSpec.hs
> +    arbitrary = SlotNo <$> choose (0, 216000)
What's the reasoning behind the choice of upper limit?

2019-07-23 03:20 UTC, jonathanknowles commented on lib/http-bridge/test/bench/Cardano/Wallet/Primitive/AddressDiscovery/Any/TH.hs
> +    anyAddressStateCheckpointSlot  W.SlotNo    sql=slot
Perhaps we could use `sql=slot_no` here too.

2019-07-23 03:20 UTC, jonathanknowles commented on lib/http-bridge/test/unit/Cardano/Wallet/HttpBridge/NetworkSpec.hs
> +    prevHash = if slot == SlotNo 0 then Hash "genesis" else mockHash prevSlotId
I like this function, as it reduces repetition elsewhere.

2019-07-23 03:20 UTC, jonathanknowles commented on lib/http-bridge/test/unit/Cardano/Wallet/HttpBridge/NetworkSpec.hs
> +    -> NetworkLayer (HttpBridge 'Mainnet) m
Why does this need to be `Mainnet`?

2019-07-23 03:20 UTC, jonathanknowles commented on lib/jormungandr/src/Cardano/Wallet/Jormungandr/Binary.hs
> +convertBlockHeader flatten h = W.BlockHeader (flatten (slot h)) (parentHeaderHash h)
```suggestion
convertBlockHeader flatten h =
    W.BlockHeader (flatten (slot h)) (parentHeaderHash h)
```
https://github.com/input-output-hk/cardano-wallet/wiki/Coding-Standards#limit-line-length-to-80-characters

2019-07-23 03:20 UTC, jonathanknowles commented on lib/jormungandr/src/Cardano/Wallet/Jormungandr/Network.hs
> +{-# LANGUAGE RecordWildCards #-}
Perhaps consider using `NamedFieldPuns` instead? When reading the code, it makes it slightly more obvious where symbols are coming from (at the expense of slightly more typing.)

2019-07-23 03:20 UTC, jonathanknowles commented on lib/jormungandr/test/integration/Cardano/Wallet/Jormungandr/NetworkSpec.hs
> +        threadDelay 5000000 -- fixme: need to fix the wait
Perhaps add a comment explaining why it's necessary to wait here?

2019-07-23 05:55 UTC, rvl commented
This PR shows how to use the simpler epoch-blind `SlotNo` for the wallet core code while using the node network layer for conversion of `SlotNo -> UTCTime` (because network layer already has this node-relevant configuration).

If we want to "keep our options open" and not remove `SlotId` from the wallet core then I'm happy enough to close this PR for now and possibly resurrect it later when we need to deal with variable epoch lengths and slot durations.

2019-07-23 13:53 UTC, KtorZ commented
> If we want to "keep our options open" and not remove SlotId from the wallet core then I'm happy enough to close this PR for now and possibly resurrect it later when we need to deal with variable epoch lengths and slot durations.

I was about to say it :grimacing: ... I like the idea and, as you said on slack, this story keeps on giving new children. So, we have to be careful about what we're trying to achieve here and keep the main goal in mind: 

- Listing transaction history

There's work to do regarding the transaction index in order to resolve inputs, there's work to do in order to handle evolving blockchain parameters. And this will have an impact on the transaction listing for sure but it sounds out-of-scope for me out the moment. 
So, let's allocate proper time to think correctly about how we maintain blockchain parameters as they go through protocol updates, and for now, let's keep the focus on handling transaction history with the slot time we're given on start-up :)

2019-07-23 13:53 UTC, closed without merging